spring.application.name=api

# Conexão com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_javap2
spring.datasource.username=postgres
spring.datasource.password=165352
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: cria/atualiza tabelas automaticamente!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true